- app/mentor-profile/components/MySessionsTab.tsx
> mentor my session fixed

- app/api/user/[id]/get_coffee_chat_time/route.ts
- debugging/apitest.http
> create a new api to return confirmed coffee chat time

- app/components/Navbar.tsx
- app/hooks/useMentorStatus.ts
- app/page.tsx
修复了一个问题 在landing page和 header上面 become a mentor 按钮会闪一下然后消失
> fix the become a mentor button flash issue

- app/api/mentor/update/[id]/route.ts
- app/lib/availability.ts
- app/lib/mentor.ts
- app/mentee-profile/[id]/page.tsx
- app/mentee-profile/components/MySessionsTab.tsx
- app/mentor-profile/[id]/page.tsx
- app/mentor-profile/components/AvailabilityTab.tsx
- app/mentor-profile/components/MySessionsTab.tsx
- package-lock.json
- package.json
> mentor and mentee profile changed

- app/api/meet/generate/route.ts
- app/types/meet.ts
- debugging/apitest.http
- package.json
- pnpm-lock.yaml
> allow api/meet/generate to generate meet link

- app/mentee-profile/[id]/page.tsx
- app/mentee-profile/components/MySessionsTab.tsx
- app/mentor-profile/components/AvailabilityTab.tsx
- app/mentor-profile/components/MySessionsTab.tsx
- package-lock.json
> mentor-profile availability fixed

- .gitignore
- app/mentor-list/ClientSearchPage.tsx
- app/mentor-list/components/SearchFilters.tsx
- app/mentor-profile/[id]/page.tsx
- app/mentor-profile/components/AvailabilityTab.tsx
- app/mentor/[id]/MentorDetailsPage.tsx
- types/index.ts
Fixed an issue that availability tab is not auto selected after sign up
Add a company filter to the mentor list page 
Fixed an issue on mentor details page, the title and company are not displayed
> fix multiple issues

- app/api/appointment/report_issue/route.ts
- app/api/appointment/update/route.ts
- app/lib/email.ts
- app/mentee-profile/[id]/page.tsx
- app/mentor-profile/[id]/page.tsx
- app/mentor-profile/components/MySessionsTab.tsx
- app/types/email.ts
- app/types/email_template/SessionCanceledEmail.tsx
- app/types/email_template/session_report_issue.tsx
> profile fixed

- app/api/user/[id]/get_coffee_chat_time/route.ts
- app/mentor/[id]/MentorDetailsPage.tsx
> Feature/oscarzeng bugfix 7.24

- app/mentee-profile/[id]/page.tsx
- app/mentor-profile/[id]/page.tsx
> fix the bugs for uploadidng image

- app/mentor-list/components/MentorGrid.tsx
> display the price of the first service that is not free coffee chat

- app/api/profile_image/update/route.ts
- app/mentee-profile/[id]/page.tsx
- app/mentor-profile/[id]/page.tsx
> fix bugs of profile image upload

- app/api/appointment/update/route.ts
- app/mentee-profile/components/MySessionsTab.tsx
- app/mentor-profile/[id]/page.tsx
- app/mentor-profile/components/MySessionsTab.tsx
- app/types/email_template/SessionCanceledEmail.tsx
> my sessions updated

- app/components/MentorAvailability/index.tsx
- app/mentor/[id]/MentorDetailsPage.tsx
- package-lock.json
- package.json
> fix latest bugs 7.25

- app/components/MentorAvailability/index.tsx
- app/mentor/[id]/MentorDetailsPage.tsx
> truncate time slot price

- app/api/appointment/report_issue/route.ts
- app/lib/email.ts
- app/mentee-profile/components/MySessionsTab.tsx
- app/mentor-profile/components/MySessionsTab.tsx
- app/types/email.ts
- app/types/email_template/SessionReportIssueReceiptEmail.tsx
> invalid date and report issue updated

- app/components/ChatWidget.tsx
- app/signup/MentorSignup.tsx
> onboarding profile picture upload & chatbot bug fix

- app/mentee-profile/[id]/page.tsx
- app/mentor-profile/[id]/page.tsx
- app/page.tsx
- app/signup/MentorSignup.tsx
> multiple bug fixes

- app/page.tsx
> mobile screen become mentor/mentee button

- app/components/GlobalPromoBanner.tsx
- app/components/globalPromoBanner.module.css
- app/layout.tsx
- app/signup/MenteeSignup.tsx
- app/signup/MentorSignup.tsx
- app/signup/signupProcess.module.css
> mentor & mentee onboarding fix

- app/components/GlobalPromoBanner.tsx
- app/components/MentorAvailability/index.tsx
- app/mentor-list/components/MentorGrid.tsx
> coffee chat banner fix

- app/mentor-list/components/MentorGrid.tsx
- app/mentor-list/components/SearchFilters.tsx
- app/mentor-list/components/TopSort.tsx
- app/mentor-list/search.module.css
- types/index.ts
> rating sort

- app/mentor-list/ClientSearchPage.tsx
- app/mentor-list/search.module.css
- app/mentor/[id]/MentorDetailsPage.tsx
- app/mentor/[id]/mentorDetails.module.css
> mobile payment ui fix

- app/mentor-list/search.module.css
> button scroll fix

- app/mentor-list/components/SearchFilters.tsx
> filter order change

- app/mentor-list/components/SearchFilters.tsx
- app/signup/RoleSelect.tsx
> filter update & mentee onboarding disabled
